name: Deploy to GitHub Pages
env:
  PUBLISH_DIR: /release/wwwroot

# Run workflow on every push to the master branch
on:
  push:
    branches:
      - master
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.2
        with:
          # Optional SDK version to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x
          dotnet-version: 6.0.x
          
        # publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish ./BlazorApp2/BlazorApp2.csproj -c Release -o release --nologo
        
        # changes the base-tag in index.html from '/' to 'Anime-WebApp' to match GitHub Pages repository subdirectory
        # - name: Change base-tag in index.html from / to Anime-WebApp
        # run: sed -i 's/<base href="\/" \/>/<base href="\/Anime-WebApp\/" \/>/g' release/wwwroot/index.html

      - name: Rewrite base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: release/wwwroot/index.html
          base_href: /Anime-WebApp/
        
        # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
